apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  labels:
    run: mosquitto
spec:
  type: NodePort 
  ports:
  - port: 1883
    protocol: TCP
    nodePort: 30789
  selector:
    app: mosquitto
