apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgproc-deployment
spec:
  selector:
    matchLabels:
      app: imgproc
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: imgproc
    spec:
      containers:
      - name: imgproc
        image: jroshanucb/imgproc:latest
